# Generated by Django 5.2.2 on 2025-06-07 09:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hopdong', '0001_initial'),
        ('phi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CongNo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('ma_cong_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Mã công nợ')),
                ('so_tien_no', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền nợ')),
                ('ngay_phat_sinh', models.DateField(verbose_name='Ngày phát sinh')),
                ('ngay_dao_han', models.DateField(verbose_name='Ngày đáo hạn')),
                ('da_thanh_toan', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('ngay_thanh_toan', models.DateField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('phi_tre_han', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Phí trễ hạn')),
                ('ty_le_phi_tre_han', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), max_digits=5, verbose_name='Tỷ lệ phí trễ hạn (%/ngày)')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('hop_dong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cong_no_list', to='hopdong.hopdong', verbose_name='Hợp đồng')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Công nợ',
                'verbose_name_plural': 'Công nợ',
                'db_table': 'cong_no',
                'ordering': ['-ngay_phat_sinh'],
            },
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('ma_thanh_toan', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Mã thanh toán')),
                ('so_tien', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền thanh toán')),
                ('phuong_thuc_thanh_toan', models.CharField(choices=[('tien_mat', 'Tiền mặt'), ('chuyen_khoan', 'Chuyển khoản'), ('the_tin_dung', 'Thẻ tín dụng'), ('vi_dien_tu', 'Ví điện tử'), ('internet_banking', 'Internet Banking')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('ngay_thanh_toan', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thanh toán')),
                ('trang_thai', models.CharField(choices=[('cho_xu_ly', 'Chờ xử lý'), ('thanh_cong', 'Thành công'), ('that_bai', 'Thất bại'), ('huy_bo', 'Hủy bỏ')], default='cho_xu_ly', max_length=20, verbose_name='Trạng thái')),
                ('ma_giao_dich_ngan_hang', models.CharField(blank=True, max_length=100, verbose_name='Mã giao dịch ngân hàng')),
                ('ten_ngan_hang', models.CharField(blank=True, max_length=100, verbose_name='Tên ngân hàng')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ly_do_that_bai', models.TextField(blank=True, verbose_name='Lý do thất bại')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('hop_dong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanh_toan_list', to='hopdong.hopdong', verbose_name='Hợp đồng')),
                ('nhan_vien_xu_ly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thanh_toan_xu_ly', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên xử lý')),
                ('phi_thanh_toan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanh_toan_list', to='phi.phithanhtoan', verbose_name='Phí thanh toán')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'db_table': 'thanh_toan',
                'ordering': ['-ngay_thanh_toan'],
            },
        ),
    ]
